# Generated by Django 2.0 on 2018-02-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('path', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('duration', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('contents', models.ManyToManyField(to='interface.Content')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('resolution', models.CharField(max_length=15)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('timelines', models.ManyToManyField(to='interface.Timeline')),
            ],
        ),
    ]
