# Generated by Django 2.0 on 2018-02-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20180205_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_format',
            field=models.CharField(default='jpg', max_length=5),
            preserve_default=False,
        ),
    ]
