# Generated by Django 2.0 on 2018-02-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20180215_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderindex', models.PositiveIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Content')),
            ],
        ),
        migrations.CreateModel(
            name='ViewTimelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderindex', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='view',
            name='timelines',
        ),
        migrations.AddField(
            model_name='viewtimelines',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Timeline'),
        ),
        migrations.AddField(
            model_name='viewtimelines',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.View'),
        ),
        migrations.AddField(
            model_name='timelinecontents',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Timeline'),
        ),
    ]
