# Generated by Django 2.0 on 2018-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20180220_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinecontents',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
