# Generated by Django 2.0 on 2018-02-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_timelinecontents_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='duration',
        ),
    ]
