# Generated by Django 2.0 on 2018-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='timeline',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='view',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
