# Generated by Django 2.0 on 2018-02-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_auto_20180221_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='timeline',
            new_name='timelines',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='view',
            new_name='views',
        ),
    ]
