# Generated by Django 2.0 on 2018-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20180227_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinecontents',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='viewtimelines',
            name='permissions',
        ),
        migrations.AddField(
            model_name='timeline',
            name='permissions',
            field=models.ManyToManyField(to='interface.UserProfile'),
        ),
        migrations.AddField(
            model_name='view',
            name='permissions',
            field=models.ManyToManyField(to='interface.UserProfile'),
        ),
    ]
