# Generated by Django 2.0 on 2018-03-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_auto_20180306_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='has_changed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='has_changed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='view',
            name='has_changed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
