# Generated by Django 2.0 on 2018-03-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_auto_20180308_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='file_format',
            new_name='file_type',
        ),
    ]
