# Generated by Django 2.0 on 2018-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_auto_20180309_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
