# Generated by Django 2.0 on 2018-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_content_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
