# Generated by Django 2.0 on 2018-03-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_auto_20180313_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='mac',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
