# Generated by Django 2.0 on 2018-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_auto_20180315_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
